version: '3.7'

services:
  solr:
    image: solr:latest
    container_name: boy-solr
    ports:
      - "8983:8983"
    volumes:
      - ./data:/var/solr/data
      - ./config:/var/solr/config
    command:
      - solr-start -f -p 8983 -s /var/solr/data -c gettingstarted