version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: boy-mongo
    volumes:
      - ./data:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always