version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    hostname: prometheus
    environment:
    - TZ=Asia/Shanghai
    ports:
    - 19090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries' 
      - '--web.console.templates=/usr/share/prometheus/consoles' 
      - '--storage.tsdb.retention.time=7d'
      - '--web.external-url=prometheus'
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./data:/prometheus